using System.Globalization;
using System.Text;
using LaserForge.Core.Geometry;
using LaserForge.Core.Model;

namespace LaserForge.Core.Gcode;

/// <summary>
/// Low-level G-code emitter. Takes project-space (Y-down) coordinates, converts to machine space,
/// suppresses repeated modal words (G1, S, F) to keep the stream small, and tracks time/distance.
/// </summary>
public sealed class GcodeWriter
{
    private readonly MachineProfile _m;
    private readonly List<string> _lines = new();
    private Vec2? _pos;          // current position, project space
    private string? _motion;     // "G0" / "G1"
    private double? _s;
    private double? _f;

    public double CutDistanceMm { get; private set; }
    public double TravelDistanceMm { get; private set; }
    public double EstimatedSeconds { get; private set; }

    public IReadOnlyList<string> Lines => _lines;

    public GcodeWriter(MachineProfile machine) => _m = machine;

    public void Comment(string text) => _lines.Add("; " + text.Replace('\n', ' '));

    public void Raw(string line) => _lines.Add(line);

    public void Header()
    {
        Comment($"Generated by {AppInfo.Product} {AppInfo.Version} on {DateTime.Now:yyyy-MM-dd HH:mm}");
        Comment($"Machine: {_m.Name}, bed {Fmt(_m.BedWidthMm)} x {Fmt(_m.BedHeightMm)} mm, S max {Fmt(_m.MaxSpindleS)}");
        Raw("G21");            // millimetres
        Raw("G90");            // absolute
        Raw(_m.DynamicPower ? "M4 S0" : "M3 S0"); // laser enabled at zero power; G1 moves set S
        _s = 0;
    }

    public void Footer()
    {
        Raw("M5");
        if (_m.ReturnToOrigin) Raw("G0 X0 Y0");
        Raw("M2");
    }

    /// <summary>Laser-off travel move.</summary>
    public void Rapid(Vec2 p)
    {
        if (_pos is { } cur && Vec2.Distance(cur, p) < 1e-4) return;
        var sb = new StringBuilder();
        if (_motion != "G0") { sb.Append("G0"); _motion = "G0"; }
        AppendXY(sb, p);
        _lines.Add(sb.ToString());
        Account(p, _m.TravelSpeedMmMin, cutting: false);
    }

    /// <summary>Burning (or, with power 0, laser-off at feed rate) linear move.</summary>
    public void Cut(Vec2 p, double powerS, double feedMmMin)
    {
        if (_pos is { } cur && Vec2.Distance(cur, p) < 1e-4) return;
        var sb = new StringBuilder();
        if (_motion != "G1") { sb.Append("G1"); _motion = "G1"; }
        AppendXY(sb, p);
        double s = Math.Round(powerS, 1);
        if (_s != s) { sb.Append(" S").Append(Fmt(s)); _s = s; }
        if (_f != feedMmMin) { sb.Append(" F").Append(Fmt(feedMmMin)); _f = feedMmMin; }
        _lines.Add(sb.ToString());
        Account(p, feedMmMin, cutting: powerS > 0);
    }

    public Vec2? Position => _pos;

    private void Account(Vec2 p, double feed, bool cutting)
    {
        double d = _pos is { } cur ? Vec2.Distance(cur, p) : 0;
        if (cutting) CutDistanceMm += d; else TravelDistanceMm += d;
        if (feed > 0) EstimatedSeconds += d / feed * 60.0;
        _pos = p;
    }

    // Only axes that change are written: raster rows then become "X12.3 S400", roughly halving file size
    // and the number of bytes GRBL has to parse per pixel run.
    private void AppendXY(StringBuilder sb, Vec2 p)
    {
        var mp = ToMachine(p);
        string x = Fmt(mp.X), y = Fmt(mp.Y);
        bool writeX = _lastX != x, writeY = _lastY != y;
        if (!writeX && !writeY) writeX = true;
        if (writeX) { if (sb.Length > 0) sb.Append(' '); sb.Append('X').Append(x); _lastX = x; }
        if (writeY) { if (sb.Length > 0) sb.Append(' '); sb.Append('Y').Append(y); _lastY = y; }
    }

    private string? _lastX, _lastY;

    public Vec2 ToMachine(Vec2 p) => _m.FlipY ? new Vec2(p.X, _m.BedHeightMm - p.Y) : p;

    public static string Fmt(double v)
    {
        var s = Math.Round(v, 3).ToString("0.###", CultureInfo.InvariantCulture);
        return s == "-0" ? "0" : s;
    }
}
